### ISSUE TITLE
Game Crash On Loading - Concurrent Modification Exception

### ISSUE THREAD

**Issue by Sixdd6** [PersonTheCat/ore_stone_variants#125] opened 2021-05-25 20:52 UTC
Basically as the title says, log is posted [here](https://gist.github.com/Sixdd6/c997b59ab9c34b5d5ba54c232075a60d)

For reference I am attempting to load with a x256 texture pack with Optifine installed, not sure if that old texture issue is still relevant or not.

**Comment by PersonTheCat** [comment] 2021-05-25 23:37
Hello. I have been aware of this issue for some time and have just recently begun working on a fix for it. The problem is that I can't verify it because this does not occur for me. You can try this new build out below and let me know if the problem goes away. Make sure to try it multiple times, because this is not a guaranteed crash as it has to do with multithreading and is essentially random. 

If the problem does not go away when using this new build, I really cannot fix it unless we can narrow this issue down to a single mod that causes the problem. If the problem is coming from Optifine, I will _not_  fix it.

In any case, I hope this works! Let me know how it goes if you try it out and thanks in advance for your help!

[Ore_Stone_Variants-6.2.zip](https://github.com/PersonTheCat/ore_stone_variants/files/6542955/Ore_Stone_Variants-6.2.zip)

**Comment by Sixdd6** [comment] 2021-05-25 23:46
I'll give it a try right now.

**Comment by Sixdd6** [comment] 2021-05-26 00:23
So far,
Minimal environment with forge and optifine, loaded fine 10 out of 10 times.
200+ mod environment with optifine, loaded fine 10 out of 10 times.

Seems you've fixed it.

**Comment by PersonTheCat** [comment] 2021-05-26 00:24
Awesome! Thanks for your help. The next update is a bug fix update for 1.16, so let me know if you encounter any other issues and I'll patch em up.

**Comment by PersonTheCat** [comment] 2021-06-28 01:42
I've actually implemented a different fix for this issue in 6.2. The collection that was throwing this exception is no longer even getting modified. It's definitely a bit of a hack, but that's what it took to make this error completely impossible in the newer versions. I'll close this now.

**Closed by PersonTheCat** 2021-06-28 01:42 UTC
