### ISSUE TITLE
Crash when trying to run with Underground Biomes.

### ISSUE THREAD

**Issue by Dulciphi** [PersonTheCat/ore_stone_variants#30] opened 2018-07-10 09:42 UTC
[latest.log](https://github.com/PersonTheCat/ore_stone_variants/files/2177324/latest.log). Scroll down for further details.

The crash occurs in a newly generated instance with newly generated configs. 

Modslist - Just the basics:
forge-1.12.2-14.23.4.2717.jar
OpenEye-1.12.2-0.8.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
FastLeafDecay-v14.jar
Hwyla-1.8.26-B41_1.12.2.jar
jei_1.12.2-4.11.0.202.jar
journeymap-1.12.2-5.5.2.jar
UndergroundBiomesConstructs-1.12-1.2.1.jar
ore_stone_variants-3.1.jar
Wawla-1.12.2-2.5.257.jar

The instance runs with UBC disabled. The instance also runs with UBC enabled and Ore Stone Variants disabled. I also tried running with both OSV and UBC enabled but B:UBifyOres set to false. (UBifyOres is a UBC config option that tells UBC whether or not to retexture ores that are placed in UBC stone). 

In case you're wondering why anyone would want to run both Underground Biomes and Ore Stone Variants, that's because both mods do different things. I want the stones that UBC adds. UBC does a great job of retexturing ores to fit with its own stone. It handles mod-added ores, but it cannot handle mod-added stones. It also can't handle Vanilla Sandstone and hardened clay as well as other Vanilla stone variants that were added since 1.8. 

OSV, on the other hand, can stitch any ore overlay onto any block background, but it doesn't have the blocks. 

I was hoping to get them working together so that I don't have to choose between them.

**Comment by PersonTheCat** [comment] 2018-07-10 15:45
Thanks. OSV actually supports UBC by default. I'm fact, it's supposed to go so far as to test whether UBC has already created a variant for any given ore type and automatically create it using its stone types, if not. I must have just broken it in a recent patch in reformatting the code. Sorry about that! I'll try to fix that today.

**Comment by Dulciphi** [comment] 2018-07-10 16:39
Oh, that's some nice support out of the box. I'll be checking back for that update then. 

Thank you for your great work

**Comment by PersonTheCat** [comment] 2018-07-10 22:57
Okay. So, I actually tried to look into this, but did not experience a crash. Looking at the log you sent me, it seems like the problem is occurring when there are no blocks registered whatsoever. I will definitely fix that by the next update. In the meantime, you should be able to just add any dynamic block in the config file and things will boot normally. Kind of a weird issue. Sorry about that!

**Comment by PersonTheCat** [comment] 2018-07-13 16:55
Having tested this mod pretty consistently over the past few days, I believe this problem (and others related to it) have been fixed. I will go ahead and close this issue. Please let me know of any other issues you encounter and I'll get to them as soon as possible.

**Closed by PersonTheCat** 2018-07-13 16:55 UTC

**Comment by Dulciphi** [comment] 2018-07-17 18:05
No worries. That was exactly the issue. I'm still experimenting with OSV at the moment. I have a frustrating desire to use UBC stones for the strata, OSV to add ores to existing vanilla stone variants (like the sandstone in deserts and the hardened clay in mesas), while also having Geolosys indicate those ores. 

Maddeningly, having Geolosys in the mix makes all ore deposits generate as solid, poo-shaped blobs, so that has to go. But I noticed another issue. There were randomly placed coal ore deposits in blue hardened clay. ..in the plains biome. I'm not sure if I've misunderstood how OSV places ores. Does it only replace stone of the same type used in the ore's base block? Or do I have to specify which block I want that particular variant to replace? 

For example, I added 
            iron_ore,minecraft:stained_hardened_clay:*
            iron_ore,minecraft:red_sandstone
to my ore_stone_variants.cfg file, thinking that those ores would only show up in existing stone of that type (eg in Mesa biomes). What I got was deposits of blue clay iron ore and red_sandstone iron ore plopped in the middle of UBC quartzite strata in a plains biome. Like I said, the deposits were poo-shaped, meaning this could have been due to Geolosys interfering.

**Comment by PersonTheCat** [comment] 2018-07-17 18:39
No, OSV ores will definitely only spawn in their background blockstates. What can change that is Geolosys. I actually completely disable my own generation and use their API to spawn the ores, instead. There was a bug where variants often got spawned in the wrong blocks for non-stone blocks. I submitted a pull request to try and fix it, but I don't think the dev is quite ready for another release yet. In the meantime, if you do want to keep using OSV + Geolosys together, you can disable Geolosys support in the config file to work around that. I don't have working sample blocks implemented yet anyway.

**Comment by Dulciphi** [comment] 2018-07-17 21:22
Ahh. Ok I'll try again just with vanilla ores, OSV and UBC. That will give me a chance to testif OSV is automatically generating those ores for which UBC already has variants.

**Comment by PersonTheCat** [comment] 2018-07-17 22:43
Thanks. Please let me know, if it is. It shouldn't be!
