### ISSUE TITLE
(1.16.4) Textures don't load for some people

### ISSUE THREAD

**Issue by KillJestah** [PersonTheCat/ore_stone_variants#109] opened 2021-01-08 06:55 UTC
Just downloaded the 1.16.4 version of the mod, and everything works as it should except the textures, which use the 'texture missing' textures.

**Comment by GnomTocha** [comment] 2021-01-08 09:30
![2021-01-08_11 27 52](https://user-images.githubusercontent.com/75666317/103998516-282a8780-51ad-11eb-8358-192ec19460bb.png)
![2021-01-08_11 28 09](https://user-images.githubusercontent.com/75666317/103998551-2e206880-51ad-11eb-8ed0-854fb1e3c226.png)

**Comment by PersonTheCat** [comment] 2021-01-08 13:02
Thanks. Forgot to regenerate my old resources. I'll get this fixed right away.

**Comment by PersonTheCat** [comment] 2021-01-08 15:12
Hey, I did try regenerating these today and mine are all working. Using forge 35.1.36. But I did discover that they're getting stored under the `minecraft` namespace instead of `osv`. I'll fix that today, upload here, and if you can help me confirm whether that fixes the issue, that would be awesome!

**Comment by KillJestah** [comment] 2021-01-09 20:34
Alrighty, I'll check it out as soon as the new version is up.

**Comment by KillJestah** [comment] 2021-01-09 20:51
![fixed](https://user-images.githubusercontent.com/76569328/104108410-465db980-5279-11eb-89b5-f5397e345284.png)

Apparently it works fine now, without a new version after I downloaded more mods?? Seems to be a slight bug that randomly happens or something when reloading in.

**Comment by WenXin20** [comment] 2021-01-09 20:56
They are still missing textures for me.

**Comment by KillJestah** [comment] 2021-01-09 20:58
Yeah, I started a test world and it seems like the first time or so you load in a world, all of the textures will not work. A second or third time they do.

**Comment by WenXin20** [comment] 2021-01-09 21:02
I've used the same world multiple times already though.

**Comment by WenXin20** [comment] 2021-01-09 21:07
Did you remove any mods from you modpack?

**Comment by KillJestah** [comment] 2021-01-09 21:12
Nope, I did update a few of them though.

**Comment by GnomTocha** [comment] 2021-01-09 21:15
See what identical mods you have installed.

**Comment by KillJestah** [comment] 2021-01-09 21:18
I went through the mods I have, and none are identical. It seems to be an issue with the mod itself where it will decide to work, but not load up textures.

**Comment by PersonTheCat** [comment] 2021-01-09 21:18
Seems like a lot of people experiencing this issue are using Optifine. Can anyone confirm whether this is involved?

**Comment by KillJestah** [comment] 2021-01-09 21:33
No Optifine on my side, it's incompatible with another mod I have.

**Comment by PersonTheCat** [comment] 2021-01-09 21:34
@KillJestah Any idea which one in particular? If you know a single mod that will guarantee this to not work, I'll try it out in a couple hours.

**Comment by KillJestah** [comment] 2021-01-09 21:35
fpsreducer is the only one I use.

**Comment by PersonTheCat** [comment] 2021-01-09 21:37
Cool. I'll give that a shot! Being able to narrow it down like that helps me see where the problem is occurring. I'll take a look at this and try to fix it today. Thanks for your help!

**Comment by KillJestah** [comment] 2021-01-09 21:39
No problem! I think this is a cool mod that should already be a thing in Vanilla, so thanks for the mod!

**Comment by WenXin20** [comment] 2021-01-09 21:49
Hmm, I'm not using fpsreducer though.

**Comment by WenXin20** [comment] 2021-01-11 16:27
And this time I got a JEI crash when it tried to render the ores.
[Crash Report](https://gist.github.com/WenXin20/d92b2f6357fc2fdf93a5f5a013134d05)

**Comment by PersonTheCat** [comment] 2021-01-11 16:32
Hey, everybody. Sorry it took me so long, but I actually tried FPS Reducer and *still* did not experience any issues with my textures. I made two changes to see if that'll help and I'm hoping someone here can help confirm that for me.

Here's what I changed:
- Updated the old mappings which were working anymore.
- Corrected the texture namespace from `assets/minecraft` to `assets/osv`.
- Attempted to synchronize the texture pack registry in case desync was the issue before.

Here's the newest file, for anyone who wants to help. You have to unzip it since GitHub doesn't allow jar files.
[Ore Stone Variants-5.11-1.16.4.zip](https://github.com/PersonTheCat/ore_stone_variants/files/5797007/Ore.Stone.Variants-5.11-1.16.4.zip)

**Comment by PersonTheCat** [comment] 2021-01-11 16:43
@WenXin20 Was that before or after this new build?

**Comment by WenXin20** [comment] 2021-01-11 16:44
It was before

**Comment by PersonTheCat** [comment] 2021-01-11 17:00
That's weird. I tried using JEI with both version 5.10 *and* 5.11 and did not experience this crash. Everything is 100% working for me still. Let me know if you try this new build and do or do not still experience this issue.

**Comment by WenXin20** [comment] 2021-01-11 17:09
It doesn't seem to happen all the time. And it happened with sandstone that I added to the blockgroup.

**Comment by PersonTheCat** [comment] 2021-01-11 17:12
@WenXin20 Which Forge version are you using? I'm on 35.1.36.

**Comment by WenXin20** [comment] 2021-01-11 17:17
I'm using the same

**Comment by GnomTocha** [comment] 2021-01-11 17:27
> Всем привет. Извините, это заняло у меня так много времени, но я действительно попробовал FPS Reducer и по- _прежнему_ не испытывал никаких проблем с моими текстурами. Я внес два изменения, чтобы посмотреть, поможет ли это, и надеюсь, что кто-то из присутствующих поможет мне это подтвердить.
> 
> Вот что я изменил:
> 
> * Обновлены старые сопоставления, которые больше не работали.
> * Исправлено пространство имен текстур с `assets/minecraft`по `assets/osv`.
> * Попытка синхронизировать реестр пакетов текстур на случай, если раньше была проблема с рассинхронизацией.
> 
> Вот самый новый файл для всех, кто хочет помочь. Вам необходимо разархивировать его, поскольку GitHub не поддерживает файлы jar.
> [Варианты рудного камня-5.11-1.16.4.zip](https://github.com/PersonTheCat/ore_stone_variants/files/5797007/Ore.Stone.Variants-5.11-1.16.4.zip)

![image](https://user-images.githubusercontent.com/75666317/104216609-55946100-544b-11eb-8466-9293433006fa.png)
I checked it on my assembly with 203 mods.

**Comment by WenXin20** [comment] 2021-01-11 17:43
My ores are also still missing their textures.

**Comment by PersonTheCat** [comment] 2021-01-11 17:50
Do you mind sharing your logs? Either one.

**Comment by WenXin20** [comment] 2021-01-11 17:56
https://gist.github.com/WenXin20/10548168bfd593b16ce7b1f0be9a5ad1

**Comment by PersonTheCat** [comment] 2021-01-11 18:10
I see. Looks like `TextureStitchEvent` is firing because your textures are getting generated, but it's not able to place the models at all because `ModelBakeEvent` isn't running. No clue why that's just not running. Don't have much control over it. 

All I can do is try a few more mods and see what induces it, but until I experience this myself, *I cannot fix it*.

**Comment by WenXin20** [comment] 2021-01-11 18:13
Yeah, I'm currently working on figuring out which mod might be causing it.

**Comment by WenXin20** [comment] 2021-01-11 18:19
I just ran it with No other mods, and the textures are still missing.
[Log](https://gist.github.com/WenXin20/b1570f0192caa95acbea1a408e707796)

**Comment by PersonTheCat** [comment] 2021-01-11 18:31
Maybe this is config related. Can you share your config file?

**Comment by WenXin20** [comment] 2021-01-11 18:37
I used a fresh instance, so the configs are the default ones.

**Comment by GnomTocha** [comment] 2021-01-11 18:38
Also
https://drive.google.com/file/d/1G6JcmEAfLMEdH33zxMz8Eb7Vgr87hGK-/view?usp=sharing

**Comment by GnomTocha** [comment] 2021-01-11 18:56
[latest.log](https://github.com/PersonTheCat/ore_stone_variants/files/5797762/latest.log)
[debug.log](https://github.com/PersonTheCat/ore_stone_variants/files/5797764/debug.log)

**Comment by WenXin20** [comment] 2021-01-11 19:16
The textures on the ores started working after I reloaded my textures.

**Comment by GnomTocha** [comment] 2021-01-11 19:17
hahahahahahah. I solved the problem in a very ridiculous and simple way. I threw the archive in the resources.zip configs into the resource packs.

**Comment by GnomTocha** [comment] 2021-01-11 19:18
![image](https://user-images.githubusercontent.com/75666317/104227724-e3c41380-545a-11eb-9959-7c9162e49a2b.png)

**Comment by PersonTheCat** [comment] 2021-01-11 19:20
Yes, this is the mod's resource pack and it is just a regular resource pack, so that should work. The problem is that the events I'm using to setup this resource pack are sometimes not running. I don't have any control over whether they run, which is what makes this such a difficult problem to deal with. I still need to figure out why they aren't for some users. 

Again, I still have not experienced this issue even one time.

**Comment by GnomTocha** [comment] 2021-01-11 19:23
I disabled it in the resource pack, but the problem did not return.

**Comment by WenXin20** [comment] 2021-01-11 19:24
Pressing `F3+T` to reload the textures, fixes the missing textures for me, but restarting the game reverts it back to missing textures.

**Comment by WenXin20** [comment] 2021-01-11 19:25
Could the issue be java or device specific?

**Comment by GnomTocha** [comment] 2021-01-11 19:40
> Нажатие `F3+T`на перезагрузку текстур исправляет недостающие текстуры для меня, но перезапуск игры возвращает ее обратно к отсутствующим текстурам.

It also helps before restarting. I can upload a folder with all the mods and drop the link.

**Comment by PersonTheCat** [comment] 2021-01-11 19:42
I doubt it's a Java issue. I believe Minecraft is bundled with its own Java RE now. Not sure about device-specific, either. Looks like we're all using Windows. I'm on Windows 10. 

@WenXin20 I just tried a completely fresh install through Overwatch and still am not experiencing any issues whatsoever. You said there are definitely no other mods? No Optifine? Are there any resource packs installed?

**Comment by PersonTheCat** [comment] 2021-01-11 19:43
@GnomTocha I can try this, but I really need to narrow it down as much as possible. The fewer changes it takes to produce this error, the easier it is to fix.

**Comment by WenXin20** [comment] 2021-01-11 19:43
Yeah, definitely no other mods or resource packs were installed. And Windows 10.

**Comment by GnomTocha** [comment] 2021-01-11 20:09
Because of the exams, I don't have much time. If possible, I will try to find a conflict myself. Here is a link to mods https://drive.google.com/file/d/16JlRHL91Waz_nmPPl45vHJy-DOKzFKXs/view?usp=sharing

**Comment by PersonTheCat** [comment] 2021-01-11 21:26
Experiencing a lot of issues and inconsistent crashes now when using Optifine. Had to try a couple different versions of Optifine until the game would even load. That being said, I still have *not* seen any missing textures, but I do suspect that it has something to do with Optifine.

@WenXin20 I tried removing the mod from my mods folder and, after reading the logs, it seems to have just installed itself. I'm wondering if that may be what happened with your instance as well.

**Comment by WenXin20** [comment] 2021-01-11 21:51
I didn't have optifine installed, I checked the video settings and it was only the vanilla settings.

**Comment by PersonTheCat** [comment] 2021-01-11 21:56
Any way you could send the log? I was still seeing Optifine in the logs, but not in game.

**Comment by WenXin20** [comment] 2021-01-11 21:58
> I just ran it with No other mods, and the textures are still missing.
> [Log](https://gist.github.com/WenXin20/b1570f0192caa95acbea1a408e707796)
I sent it a couple of comments ago.

**Comment by PersonTheCat** [comment] 2021-01-11 21:59
Oh, you're right. Thanks! Still not sure.

**Comment by WenXin20** [comment] 2021-01-12 05:21
In the pack.mcmeta, the pack format number for 1.16.4 is 6, but in the file it is set to 3. Could that be why this is happening?

**Comment by GnomTocha** [comment] 2021-01-12 17:24
Launched only osv without other mods(also without Optifine). Forge 35.1.28
[debug.log](https://github.com/PersonTheCat/ore_stone_variants/files/5803732/debug.log)
[latest.log](https://github.com/PersonTheCat/ore_stone_variants/files/5803733/latest.log)
![2021-01-12_19 17 14](https://user-images.githubusercontent.com/75666317/104349233-b7b89900-5513-11eb-9d9f-d7b1b3d5168b.png)

**Comment by GnomTocha** [comment] 2021-01-12 17:51
Tried the mod with forge 35.1.36 without any other mods and the problem persists. Then I changed tlaucher to official mojang. Unfortunately, nothing has changed.

**Comment by PersonTheCat** [comment] 2021-01-27 00:58
Just wanted to give a quick update and say that I've now tried running this mod in 4 different environments, 2 different computers, 3 different operating systems, and once in a virtual machine. I've tried running it directly in my IDE, by downloading it manually from CurseForge, and through the Overwolf launcher. I have **not** experienced this issue even once. If anyone here has access to a second computer or operating system where they can test this a second time, please try that and update me with the results. 

This is officially one of the most complicated bugs I've ever experienced and I can't fix it until I can figure out what's causing it. I was hoping this would be a race condition that I could just find and fix, but I feel confident at this point that we can rule that out. I'm at a stalemate now and don't believe there's much else I can do.

**Comment by KillJestah** [comment] 2021-02-26 22:08
It's been a while, but as of 1.11, the problem still randomly persists. Most often, it seems to happen when the mod tries to make Ore blocks using the Quark stones.

**Comment by PersonTheCat** [comment] 2021-02-26 22:20
I've worked really, *really* hard to reproduce this issue. Across 3 machines, one virtual machine, and two different operation systems (not counting distributions), this problem just does not occur for me. 

That being said, version 6.0 will be out soon. One of the biggest features it introduces is concrete JSON model generation, meaning the new models will load just like all the others provided the resource pack is enabled in time. It is also working for me, but it hasn't really been thoroughly tested by other people. I'll share a build of that here tonight for anyone who wants to try it out and see if the problem goes away.

**Comment by KillJestah** [comment] 2021-02-26 22:24
Hopefully that will finally solve the issue. Sorry you've had to go through so much for a problem that seemingly doesn't exist for your side.

**Comment by PersonTheCat** [comment] 2021-02-26 22:40
Definitely! This is without a doubt the most elusive problem I've ever seen. Sometimes I genuinely wonder if it actually exists because I've just never seen it. I know it does, though. Hopefully these models will do it!

**Comment by PersonTheCat** [comment] 2021-02-27 03:58
Here's the latest build for anyone who wants to help me test. Note that this includes some of the biggest changes I've ever made to the mod internally. I'm expecting quite a few bugs to still be around (and especially crashes), but on the surface, everything is working for me! 

Let me know especially if you try this out and the textures are or are not working for you now. Be aware that `resources.zip` no longer exists and was replaced with a directory, `resources`. This is intended to avoid problems with anti-virus software and other processes opening the file while the mod is still attempting to write into it.
[Ore Stone Variants-6.0-Jeremiah.zip](https://github.com/PersonTheCat/ore_stone_variants/files/6053690/Ore.Stone.Variants-6.0-Jeremiah.zip)

**Let me know especially if you try this out and the textures are or are not working for you now.** Be aware that `resources.zip` no longer exists and was replaced with a directory, `resources`. This is intended to avoid problems with anti-virus software and other processes opening the file while the mod is still attempting to write into it.

Also, feel free to join the [Discord server](https://discord.gg/UNsXfvA) because I'll be posting updates to this file over the next few days in preparation for a release. Thanks for your help!

**Comment by KillJestah** [comment] 2021-02-27 05:44
Okay, everything seems to be working fine now! This version seems to work pretty well, I tried out a few worlds and it seems to load in each time.

![2021-02-26_21 41 08](https://user-images.githubusercontent.com/76569328/109376763-afc27780-787b-11eb-9762-e8819143807f.png)

**Comment by PersonTheCat** [comment] 2021-02-27 05:50
Hey, thanks for the update! This is *really* great news. I think a couple of us are still experiencing the issue over on Discord, but I'm really relieved to hear there's at least some improvement.

**Comment by PersonTheCat** [comment] 2021-03-07 21:54
This ticket has gone through a lot of changes yet again. While there could be some improvements to compatibility with other mods, I currently believe that these textures are working as expected, and thus I am closing this issue for now. 

Because I never experienced this problem firsthand, it may come back up in a later version of the mod (6.1+). If that is the case, please create a new issue and we'll look back into it.

Thanks everyone for your help on this issue! This was tough.

**Closed by PersonTheCat** 2021-03-07 21:54 UTC
Labels: bug, help wanted
