### ISSUE TITLE
Crash Caused by Config

### ISSUE THREAD

**Issue by Voxel-Friend** [PersonTheCat/ore_stone_variants#16] opened 2018-06-20 00:05 UTC
Enabling default quartz generation causes this crash:
https://gist.github.com/Voxel-Friend/dad9f3ed3b7905adc215f4fecfb85412
Can recreate this with just OSV and forge 14.23.4.2708

**Comment by PersonTheCat** [comment] 2018-06-20 06:19
A quick update. I actually finished what I was working on much more quickly than expected and was also able to implement a workaround for this problem. I'll put a new release out tonight. Please try it as soon as you get the chance and verify that the problem is fixed for you, as well.

Thanks again!

**Comment by Voxel-Friend** [comment] 2018-06-21 03:34
Works Like a Charm!

**Comment by PersonTheCat** [comment] 2018-06-21 03:51
Cool! I'll go ahead and close this issue.

**Closed by PersonTheCat** 2018-06-21 03:51 UTC
