### ISSUE TITLE
Crash on load (Index Out of Bounds) with version 4.0 and greater.

### ISSUE THREAD

**Issue by Zarepheth** [PersonTheCat/ore_stone_variants#42] opened 2018-10-12 01:50 UTC
When attempting to use Ore Stone Variants version 4.0 and greater, Minecraft crashes during launch. Rolling back to version 3.9 allows Minecraft to finish loading and the game to work.

Since no one else has reported this issue, did I miss a change in the configuration file format between versions 3.x and 4.x?

Full log here: [https://paste.ee/p/1C0sV](https://paste.ee/p/1C0sV)

Start of stack trace:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ore Stone Variants (ore_stone_variants)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at personthecat.mod.objects.blocks.BlockEntry.splitEntry(BlockEntry.java:71)
	at personthecat.mod.config.Cfg.allAllUsed(Cfg.java:799)
	at personthecat.mod.config.Cfg.ensureMissingGroupsAreRegistered(Cfg.java:784)
	at personthecat.mod.config.Cfg.postOrePropertyInit(Cfg.java:686)
	at personthecat.mod.Main.preInit(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
```

**Comment by PersonTheCat** [comment] 2018-10-12 01:54
Yeah, I tried pretty hard to make sure everything stayed compatible, but the list is parsed in a totally different way, and then blocks are also registered differently now. OOB exceptions still should never occur, though. In the meantime, if you can send me your config file, I'll be able to figure out where the problem is and maybe even provide a workaround without an update. 

Thanks!

**Comment by Zarepheth** [comment] 2018-10-12 04:58
I've attached my config file (_adding a ".txt" extension, so GitHub will accept it_).

[ore_stone_variants.cfg.txt](https://github.com/PersonTheCat/ore_stone_variants/files/2471665/ore_stone_variants.cfg.txt)

I'll hunt down the v4.0 change log to see if there's anything obvious for me to manually update.

**Comment by PersonTheCat** [comment] 2018-10-12 05:17
Sure thing. So, blank lines aren't really allowed at the moment. That being said, I'll fix this to where you can use them again in 4.3. The other thing you might want to know is that "Disable Ore Names" is no longer an option. That's because all ores are registered directly to the config file now, so it's easier to just remove the ones you don't want. Let me know if you get it working and the new lines aren't added for some reason. 

Sorry about that!

**Comment by PersonTheCat** [comment] 2018-10-12 15:33
Sorry, I was multitasking as I sent that and didn't really explain it very well. It isn't the config file itself, it's actually just the array "Add Blocks Here." There's a blank line that it's trying to read from, but can't. I had previously accounted for that, but stopped in 4.0. It is definitely a bug and something I will fix by 4.3, but in the meantime, you can work around it by just deleting that extra line.

**Comment by Zarepheth** [comment] 2018-10-13 04:31
Removing that blank line in the config file enabled the version 4.2 to work.

**Comment by PersonTheCat** [comment] 2018-10-13 04:43
Cool, thanks for the confirmation. I'll leave this open until I get it fixed, hopefully soon.

**Comment by PersonTheCat** [comment] 2019-02-02 16:44
Hey, again. Sorry it took me so long to actually do something about this. I just added a check that will avoid empty lines getting processed by the mod, just like things were in previous versions. I'll go ahead and close this issue.

**Closed by PersonTheCat** 2019-02-02 16:44 UTC
Labels: bug, fixed in comments
