### ISSUE TITLE
Command listed in curse description is not in game

### ISSUE THREAD

**Issue by Goldenlion5648** [PersonTheCat/ore_stone_variants#123] opened 2021-05-13 03:32 UTC
The command "/osv put <new_ore> [<additional_ores>] in <stone_type>" is on the curse page, but "/osv" is not recognized as a command in the game.

**Comment by PersonTheCat** [comment] 2021-05-13 03:36
Which version are you running? `/osv` is absolutely a command in 1.12, 1.14, and 1.16, but the put command is for 1.16 only. It's not worth backporting due to the lack of command suggestions in 1.12.

**Comment by Goldenlion5648** [comment] 2021-05-13 03:40
ah I see, it appears the command disappears after using /reload. After relogging its back. Then I do /reload and its gone

**Comment by PersonTheCat** [comment] 2021-06-28 01:43
Was never able to reproduce this issue. I'm pretty sure it is not occurring for me and will close this issue for now. Let me know if it happens again for you and we'll try to figure out why.

**Closed by PersonTheCat** 2021-06-28 01:43 UTC
