### ISSUE TITLE
Certus quartz ore not dropping item

### ISSUE THREAD

**Issue by kragnoth** [PersonTheCat/ore_stone_variants#43] opened 2018-10-12 10:49 UTC
Current version of mod: 4.1
Forge version: 4760 (1.12.2)

This is the config file:
https://pastebin.com/dDKk47Rt

the following code looks correct and was auto generated.  Believe this worked in previous version:

{
  "originalTexture": "assets/appliedenergistics2/textures/blocks/quartz_ore.png",
  "languageKey": "tile.appliedenergistics2.quartz_ore.name",
  "hardness": 3.0,
  "harvestLevel": 0,
  "drop": "appliedenergistics2:material:0",
  "dropSilkTouch": "appliedenergistics2:quartz_ore:0",
  "dropRange": [
    1,
    2
  ],
  "xpRange": [
    2,
    5
  ],
  "additionalDropKeys": []
}

**Comment by PersonTheCat** [comment] 2018-10-12 16:51
Hello, there. I downloaded everything to see what I could reproduce, but I believe this bug was actually fixed in 4.2. The problem was that some items weren't loaded by the time I needed them, but I've moved some things around to work around that. Make sure to try the latest version and definitely let me know whether this issue is still around for you. Thanks!

**Comment by kragnoth** [comment] 2018-10-12 21:52
I'll check if I have 4.2  Might not have grabbed it because of the forge update breaking everything and not wanting to update.

**Comment by PersonTheCat** [comment] 2018-10-12 23:35
Cool. Let me know if you need anything else.

**Closed by PersonTheCat** 2018-10-12 23:35 UTC

**Comment by kragnoth** [comment] 2018-10-19 16:55
I was silly to not try this earlier btw, the fear of the 2766 update breaking a bunch of mods had me not updating anything, including forge.
